In [1]:
import pandas as pd

##Reading Data

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.head()

fever  bodyPain  age  runnyNose  diffBreathe  infectionProbability
0    102         1   67          1            0                     1
1    101         0   28          0            1                     0
2    104         1    5          1           -1                     1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fever                 3 non-null      int64
 1   bodyPain              3 non-null      int64
 2   age                   3 non-null      int64
 3   runnyNose             3 non-null      int64
 4   diffBreathe           3 non-null      int64
 5   infectionProbability  3 non-null      int64
dtypes: int64(6)
memory usage: 272.0 bytes


In [5]:
df['fever'].value_counts()

104    1
101    1
102    1
Name: fever, dtype: int64

In [6]:
df.describe()

fever  bodyPain        age  runnyNose  diffBreathe  \
count    3.000000  3.000000   3.000000   3.000000          3.0   
mean   102.333333  0.666667  33.333333   0.666667          0.0   
std      1.527525  0.577350  31.342197   0.577350          1.0   
min    101.000000  0.000000   5.000000   0.000000         -1.0   
25%    101.500000  0.500000  16.500000   0.500000         -0.5   
50%    102.000000  1.000000  28.000000   1.000000          0.0   
75%    103.000000  1.000000  47.500000   1.000000          0.5   
max    104.000000  1.000000  67.000000   1.000000          1.0   

       infectionProbability  
count              3.000000  
mean               0.666667  
std                0.577350  
min                0.000000  
25%                0.500000  
50%                1.000000  
75%                1.000000  
max                1.000000

## Train Test Splitting

In [7]:
import numpy as np

In [11]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled =np.random.permutation(len(data))
    test_set_size=int(len(data)*ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]
    

In [12]:
np.random.permutation(7)

array([0, 4, 5, 2, 6, 3, 1])

In [13]:
train,test=data_split(df,0.2)

In [14]:
x_train = train[['fever','bodyPain','age','runnyNose','diffBreathe']]

In [15]:
x_train.to_numpy()

array([[102,   1,  67,   1,   0],
       [101,   0,  28,   0,   1],
       [104,   1,   5,   1,  -1]], dtype=int64)

In [16]:
x_test=test[['fever','bodyPain','age','runnyNose','diffBreathe']].to_numpy()


In [19]:
y_train = train[['infectionProbability']].to_numpy().reshape(1,-1)
y_test = train[['infectionProbability']].to_numpy().reshape(1,-1)

In [20]:
y_train

array([[1, 0, 1]], dtype=int64)

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
clf=LogisticRegression()
clf.fit(x_train,y_train)

ValueError: y should be a 1d array, got an array of shape (1, 3) instead.